# Generated by Django 4.2.2 on 2023-07-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=25)),
                ('CourseCategory', models.CharField(max_length=25)),
                ('CourseDescription', models.CharField(max_length=100)),
                ('CourseMentor', models.CharField(max_length=25)),
                ('VideoLink', models.CharField(default='NA', max_length=100)),
                ('ResourcesLink', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=25)),
                ('Mentee', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.IntegerField(max_length=10)),
                ('Permission', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=25)),
            ],
        ),
    ]
