# Generated by Django 4.1.7 on 2023-07-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EndUser',
        ),
    ]
