# Generated by Django 4.2.2 on 2023-07-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_rename_user_enduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserelation',
            name='CourseStatus',
        ),
    ]
