# Generated by Django 4.2.2 on 2023-07-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_remove_courserelation_coursestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseFeedback',
            field=models.CharField(default='NA', max_length=25),
        ),
    ]
