# Generated by Django 4.1.7 on 2023-07-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_course_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ResourcesLink',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='VideoLink',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
