# Generated by Django 4.1.7 on 2023-07-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_course_resourceslink_course_videolink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserelation',
            old_name='Mentor',
            new_name='CourseID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CourseMentee',
        ),
    ]
