# Generated by Django 4.2.2 on 2023-07-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_rename_mentor_courserelation_courseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseFeedback',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseRating',
            field=models.IntegerField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='NoOfRating',
            field=models.IntegerField(default='NA', max_length=10),
        ),
    ]
