# Generated by Django 4.2.2 on 2023-07-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_remove_course_coursefeedback_course_courserating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
