# Generated by Django 4.2.2 on 2023-07-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=25)),
                ('CourseCategory', models.CharField(max_length=25)),
                ('CourseDescription', models.CharField(max_length=100)),
                ('CourseRating', models.IntegerField(max_length=10, null=True)),
                ('NoOfRating', models.IntegerField(max_length=10, null=True)),
                ('CourseMentor', models.CharField(max_length=25)),
                ('VideoLink', models.CharField(default='NA', max_length=100)),
                ('ResourcesLink', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
