# Generated by Django 4.2.2 on 2023-07-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='AvailableCourse',
        ),
    ]
