# Generated by Django 4.2.2 on 2023-07-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_course_delete_avaicourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CourseRating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='NoOfRating',
        ),
    ]
